config/routes.rb
SimpleLogin::Application.routes.draw do
  root 'sessions#new'
  get "/slave" => "slave#index"
  get "/play/:id" => "slave#play", as: :play
  get "/master" => "master#index"
  get '/slave/all' => 'slave#all'
  get "/camera" => "master#camera"
  get "/slideshows" => "master#slideshows"
  post "/slideshows" => "master#slideshowcreate"
  get "/layouts" => "master#layouts"
  get "/settings" => "master#settings"

  resources :users do 
    resources :slideshows 
    resources :pictures, :only => [:new, :create, :index, :show]
  end

  delete "/users/:id/pictures/destroy" => 'pictures#destroy'
  resources :sessions, :only => [:new, :create, :destroy] #only need 3 restful routes for Sessions
  get "/signup"  => 'users#new'
  get "/signin" => 'sessions#new'
  get "/signout" => 'sessions#destroy'









end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pictures, :dependent => :destroy
  has_many :slideshows
  #this allows my form to contain a password field and use it on the model side, even though there is no field
  #in my database called password (we used encrypted_password)
  attr_accessor :password, :password_confirmation

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name,    :presence   => true,
            :length               => { :maximum => 30 }
  
  validates :last_name,    :presence   => true,
            :length               => { :maximum => 30 }
  
  validates :email,   :presence   => true,
            :format               => { :with => email_regex },
            :uniqueness           => { :case_sensitive => false }

  validates :password,  :presence => true,
            :confirmation         => true,
            :length               => { :within => 4..100 }

  #before the user gets added to DB, run this function.
  before_save :encrypt_password


  #this method encrypts the user's unencrypted login attempt and returns true if the password is a match
  def has_password?(submitted_password)
    self.encrypted_password == encrypt(submitted_password)
  end


  # class method that checks whether the user's email and submitted password are valid
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end


  private
    def encrypt_password
      # generate a unique salt if it's a new user
      # self.password uses the attr_accessor we defined above to allow me to grab the inputed password 
      self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{self.password}") if self.new_record?
    
      # encrypt the password and store that in the encrypted_password field
      self.encrypted_password = encrypt(self.password)
    end

    # encrypt the password using both the salt and the passed password
    def encrypt(pass)
      Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
    end
end

app/controllers/master_controller.rb
class MasterController < ApplicationController
  def index
    @user = current_user
  end

  def camera
  end

  def pictures
    @picture = Picture.all
    @pic = Picture.new()

  end

  def create
    @picture = Picture.new picture_params
    if @picture.save

      redirect_to '/pictures'

    else
      render :text => 'something went wrong!'
    end
  end

  #this can go pretty soon
  def slideshows
    @pictures = current_user.pictures.all
    @slideshow = current_user.slideshows.new  
  end

  def slideshowcreate
      if current_user.slideshows.create(slideshow_params)
        flash[:notice] = "new slideshow successfully created"

        redirect_to '/master'
      else
        render :text => "something went wrong :("
      end
  end
  #  end

  def layouts
  end

  def settings
  end
  
  private 
  def slideshow_params
    params.require(:picture).permit(:name, {:picture_ids => []})
  end

  def picture_params
    params.require(:picture).permit(:user_id, :avatar)
  end

end

app/views/master/index.html.erb
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
	<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
	<script src="//code.jquery.com/jquery-1.10.2.js"></script>
	<script src="//code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
	<script>
		$(function(){
			$( document ).tooltip();
		});
	</script>
	<style>
		label{
			display:inline-block;
			width: 5em;
		}
	</style>
</head>
<body>
	<div class='container'>
		<div class='row'>
			<div class='col-xs-12 col-md-6'><br>
				<a class='btn btn-primary btn-block btn-lg fa fa-picture-o fa-3x' href="<%= user_pictures_path current_user %>"> Gallery</a>
			</div>
			<div class='col-xs-12 col-md-6'><br>
				<a class='btn btn-primary btn-block btn-lg fa fa-play-circle-o fa-3x' href="<%= user_slideshows_path current_user %>"> Slideshows</a>
			</div>
		</div>
		<div class='row'> 
			<div class= 'col-xs-12 col-md-12'><br>
				<a class='btn btn-primary btn-block btn-lg fa fa-sort fa-3x' href="/users/<%= @user.id%>"> Main Menu</a>
			</div>
		</div>
	</div>
</body>

app/views/master/pictures.html.erb
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
	<div class ='container'>
		<div class ='topbar'><h1>Photos</h1></div>
		<div class='row'>
			<div>
				<% @picture.each do |p| %>
					<div class = 'col-xs-6 col-sm-4 col-md-3' > 
						<img src=" <%= p.avatar%> " class='img-rounded' alt="picture here" width='150px'><br><br>
					</div>
				<% end %>
			</div>
		</div>
		<br><br>
		<div class ='row'>
			<div class = 'col-xs-12'>
				<%= simple_form_for(:picture, :html => {:multipart => true, :class => 'form-horizontal'}, :defaults => {:input_html => {:class => 'form-control'} }) do |f| %>
				<%= f.hidden_field :user_id, :value => session[:user_id] %>
				<%= f.file_field :avatar, :class => 'btn btn-primary btn-lg btn-block'%> <br>
				<%= f.submit "Send to Photo Frame" , :class => 'btn btn-primary btn-lg btn-block'%> <br>
				<%end%>
				<a class='btn btn-warning btn-lg btn-block' href="/master">Back</a>
			</div>
		</div>
	</div>
</body>

app/views/master/slideshows.html.erb
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
<body>
	<div class ='topbar'><h1>Slideshows</h1></div>
	<div class ='container'>
		<div class ='row'>
				<div class = 'col-xs-12'>
					<%= form_tag("/slideshows", method: "post") do %>
						<br>
						<%= label_tag "picture[name]", "name" %>
						<%= text_field_tag 'picture[name]' %><br>
						<%= collection_check_boxes(:picture, :picture_ids, @pictures, :id, :avatar)  do |b| %>
							<label for="<%= b.object %>" >
								<img src="<%= b.text %>" width='150px'>
								<%= b.check_box %>
							</label>
						<% end %>
						<%= submit_tag "Make Slideshow", :class => 'btn btn-primary btn-lg btn-block' %><br>
					<% end %>
				
				</div>
		</div>
		<a class='btn btn-warning btn-lg btn-block' href="/master">Back</a>
	</div>
</body>